export const DEMO_EVENT_TYPES = [
  {
    name: "Birthday",
    slug: "birthday",
    description: "Memorable birthday celebrations tailored to every age and style.",
    image:
      "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=80",
  },
  {
    name: "Wedding",
    slug: "wedding",
    description: "Elegant wedding planning from engagement to the big day.",
    image:
      "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80",
  },
  {
    name: "Engagement",
    slug: "engagement",
    description: "Intimate and grand engagement celebrations done right.",
    image:
      "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=800&q=80",
  },
  {
    name: "Baby Shower",
    slug: "baby-shower",
    description: "Warm, joyful showers for the newest chapter ahead.",
    image:
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&q=80",
  },
  {
    name: "Anniversary",
    slug: "anniversary",
    description: "Romantic milestones planned with care and elegance.",
    image:
      "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800&q=80",
  },
  {
    name: "Corporate",
    slug: "corporate",
    description: "Professional events that impress teams and clients.",
    image:
      "https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&q=80",
  },
  {
    name: "Surprise Party",
    slug: "surprise-party",
    description: "Flawlessly secret surprises that land perfectly.",
    image:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80",
  },
  {
    name: "Kids Party",
    slug: "kids-party",
    description: "Fun-filled themed parties kids never forget.",
    image:
      "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=800&q=80",
  },
  {
    name: "Proposal",
    slug: "proposal",
    description: "Cinematic proposal setups for once-in-a-lifetime yeses.",
    image:
      "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=800&q=80",
  },
  {
    name: "Custom Event",
    slug: "custom-event",
    description: "Fully custom celebrations designed around your vision.",
    image:
      "https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=800&q=80",
  },
] as const;

export const DEMO_PACKAGES = [
  {
    id: "pkg-birthday-essentials",
    name: "Birthday Essentials",
    slug: "birthday-essentials",
    description:
      "A thoughtfully curated birthday package with the essentials handled — décor, cake coordination, photography and light entertainment — so you can focus on celebrating.",
    startingPrice: 15000,
    eventTypes: ["Birthday", "Kids Party", "Surprise"],
    services: ["Decoration", "Cake", "Photography", "Entertainment"],
    images: [
      "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=1000&q=80",
    ],
    highlights: [
      "Theme decoration setup",
      "Cake coordination",
      "2-hour photography",
      "Basic entertainment",
    ],
    featured: true,
    active: true,
  },
  {
    id: "pkg-celebration-plus",
    name: "Celebration Plus",
    slug: "celebration-plus",
    description:
      "A complete celebration package covering décor, photo & video, cake, entertainment and dedicated event coordination for a seamless experience.",
    startingPrice: 30000,
    eventTypes: ["Birthday", "Anniversary", "Engagement", "Baby Shower"],
    services: [
      "Decoration",
      "Photography",
      "Videography",
      "Cake",
      "Entertainment",
      "Event Coordination",
    ],
    images: [
      "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=1000&q=80",
    ],
    highlights: [
      "Premium décor styling",
      "Photo + video coverage",
      "Cake & entertainment",
      "On-day event coordinator",
    ],
    featured: true,
    active: true,
  },
  {
    id: "pkg-signature",
    name: "Signature Celebration",
    slug: "signature-celebration",
    description:
      "Our flagship end-to-end experience — premium décor, full media coverage, catering support, venue assistance and complete coordination from idea to celebration.",
    startingPrice: 60000,
    eventTypes: ["Wedding", "Engagement", "Corporate", "Custom Event"],
    services: [
      "Premium Decoration",
      "Photography",
      "Videography",
      "Catering",
      "Entertainment",
      "Venue",
      "Event Coordination",
    ],
    images: [
      "https://images.unsplash.com/photo-1519741497674-611481863552?w=1000&q=80",
    ],
    highlights: [
      "Premium décor & styling",
      "Full photo & video team",
      "Catering coordination",
      "Venue assistance",
      "Dedicated event manager",
    ],
    featured: true,
    active: true,
  },
  {
    id: "pkg-kids-magic",
    name: "Kids Magic Day",
    slug: "kids-magic-day",
    description:
      "Colourful kids parties with themed décor, games, return gifts and photography — designed for little smiles and calm parents.",
    startingPrice: 18000,
    eventTypes: ["Kids Party", "Birthday"],
    services: [
      "Decoration",
      "Entertainment",
      "Return Gifts",
      "Photography",
      "Cake",
    ],
    images: [
      "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=1000&q=80",
    ],
    highlights: [
      "Themed kids décor",
      "Games & host",
      "Return gifts",
      "Cake & photography",
    ],
    featured: false,
    active: true,
  },
  {
    id: "pkg-intimate-romance",
    name: "Intimate Romance",
    slug: "intimate-romance",
    description:
      "Elegant anniversary and proposal setups with romantic décor, photography and carefully planned surprise moments.",
    startingPrice: 25000,
    eventTypes: ["Anniversary", "Proposal", "Engagement"],
    services: ["Decoration", "Photography", "Music", "Event Coordination"],
    images: [
      "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=1000&q=80",
    ],
    highlights: [
      "Romantic décor styling",
      "Surprise moment planning",
      "Couple photography",
      "Ambient music setup",
    ],
    featured: true,
    active: true,
  },
  {
    id: "pkg-corporate-gather",
    name: "Corporate Gather",
    slug: "corporate-gather",
    description:
      "Professional corporate gatherings with venue support, AV coordination, catering and on-site management.",
    startingPrice: 45000,
    eventTypes: ["Corporate"],
    services: [
      "Venue",
      "Catering",
      "Entertainment",
      "Photography",
      "Event Coordination",
    ],
    images: [
      "https://images.unsplash.com/photo-1511578314322-379afb476865?w=1000&q=80",
    ],
    highlights: [
      "Venue & layout planning",
      "Catering coordination",
      "AV & stage support",
      "On-site event manager",
    ],
    featured: false,
    active: true,
  },
  {
    id: "pkg-surprise-night",
    name: "Surprise Night",
    slug: "surprise-night",
    description:
      "Secret-friendly surprise party planning with discreet coordination, décor, entertainment and photography.",
    startingPrice: 22000,
    eventTypes: ["Surprise", "Birthday"],
    services: [
      "Decoration",
      "Entertainment",
      "Photography",
      "Invitations",
      "Event Coordination",
    ],
    images: [
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1000&q=80",
    ],
    highlights: [
      "Discreet planning",
      "Reveal moment styling",
      "Guest coordination",
      "Photo coverage",
    ],
    featured: false,
    active: true,
  },
  {
    id: "pkg-baby-bloom",
    name: "Baby Bloom Shower",
    slug: "baby-bloom-shower",
    description:
      "Soft, stylish baby showers with décor, cake, photography and thoughtful guest experiences.",
    startingPrice: 20000,
    eventTypes: ["Baby Shower"],
    services: [
      "Decoration",
      "Cake",
      "Photography",
      "Return Gifts",
      "Event Coordination",
    ],
    images: [
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=1000&q=80",
    ],
    highlights: [
      "Soft theme décor",
      "Cake styling",
      "Guest favours",
      "Photo moments",
    ],
    featured: false,
    active: true,
  },
] as const;

const portfolioPool = [
  "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&q=80",
  "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=800&q=80",
  "https://images.unsplash.com/photo-1529636798458-92182e662485?w=800&q=80",
  "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80",
  "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&q=80",
  "https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=800&q=80",
  "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=80",
  "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80",
  "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=800&q=80",
  "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800&q=80",
];

export const DEMO_PHOTOGRAPHERS = [
  {
    id: "ph-ananya-rao",
    slug: "ananya-rao",
    category: "Photographers" as const,
    name: "Ananya Rao",
    profilePhoto:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1519741497674-611481863552?w=1400&q=80",
    location: "Kalpetta, Wayanad",
    bio: "Documentary-style wedding and celebration photographer capturing emotion with soft natural light and honest moments.",
    experience:
      "Worked across Kerala weddings, destination celebrations and intimate family events with a calm, unobtrusive approach.",
    yearsOfExperience: 8,
    specializations: ["Candid", "Natural Light", "Wedding Storytelling"],
    eventTypes: ["Wedding", "Engagement", "Anniversary", "Proposal"],
    portfolio: portfolioPool.slice(0, 8).map((url, i) => ({
      url,
      caption: `Frame ${i + 1}`,
      eventType: "Wedding",
      order: i,
    })),
    startingPrice: 18000,
    languages: ["English", "Malayalam", "Hindi"],
    serviceLocations: ["Kalpetta", "Wayanad", "Kozhikode", "Kochi"],
    availability: "Available",
    packages: [
      {
        name: "Half Day Story",
        price: 18000,
        hours: 4,
        description: "Intimate coverage for proposals and small celebrations.",
        includes: ["1 photographer", "Edited gallery", "Online delivery"],
      },
      {
        name: "Celebration Day",
        price: 32000,
        hours: 8,
        description: "Full celebration coverage with highlight reel option.",
        includes: ["1 photographer", "200+ edits", "Highlight reel add-on"],
      },
    ],
    rating: 4.9,
    reviewCount: 42,
    socialLinks: { instagram: "https://instagram.com", website: "https://ananyarao.com" },
    verified: true,
    featured: true,
    status: "APPROVED" as const,
    subscriptionPlan: "PREMIUM" as const,
    profileViews: 1280,
    portfolioViews: 3400,
  },
  {
    id: "ph-arjun-nair",
    slug: "arjun-nair",
    category: "Photographers" as const,
    name: "Arjun Nair",
    profilePhoto:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1400&q=80",
    location: "Kozhikode",
    bio: "Vibrant event photographer specializing in birthday parties, surprise reveals and high-energy celebrations.",
    experience: "Known for dynamic lighting setups and lively party coverage across North Kerala.",
    yearsOfExperience: 6,
    specializations: ["Event Lighting", "Party Coverage", "Candid Portraits"],
    eventTypes: ["Birthday", "Surprise", "Kids Party", "Corporate"],
    portfolio: portfolioPool.slice(2, 10).map((url, i) => ({
      url,
      caption: `Party ${i + 1}`,
      eventType: "Birthday",
      order: i,
    })),
    startingPrice: 12000,
    languages: ["English", "Malayalam"],
    serviceLocations: ["Kozhikode", "Malappuram", "Wayanad"],
    availability: "Available",
    packages: [
      {
        name: "Party Essentials",
        price: 12000,
        hours: 3,
        description: "Perfect for home birthdays and intimate gatherings.",
        includes: ["1 photographer", "100 edits", "Same-week delivery"],
      },
    ],
    rating: 4.7,
    reviewCount: 28,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: true,
    status: "APPROVED" as const,
    subscriptionPlan: "PRO" as const,
    profileViews: 890,
    portfolioViews: 2100,
  },
  {
    id: "ph-meera-joseph",
    slug: "meera-joseph",
    category: "Photographers" as const,
    name: "Meera Joseph",
    profilePhoto:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=1400&q=80",
    location: "Kochi",
    bio: "Soft, elegant imagery for baby showers, maternity moments and family celebrations.",
    experience: "Specializes in gentle direction and lifestyle family storytelling.",
    yearsOfExperience: 5,
    specializations: ["Lifestyle", "Family", "Baby Shower"],
    eventTypes: ["Baby Shower", "Birthday", "Family Function", "Anniversary"],
    portfolio: portfolioPool.slice(1, 9).map((url, i) => ({
      url,
      caption: `Soft ${i + 1}`,
      eventType: "Baby Shower",
      order: i,
    })),
    startingPrice: 10000,
    languages: ["English", "Malayalam", "Tamil"],
    serviceLocations: ["Kochi", "Ernakulam", "Alappuzha"],
    availability: "Limited",
    packages: [
      {
        name: "Bloom Session",
        price: 10000,
        hours: 2,
        description: "Beautiful baby shower and family coverage.",
        includes: ["1 photographer", "80 edits", "Online album"],
      },
    ],
    rating: 4.8,
    reviewCount: 19,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: false,
    status: "APPROVED" as const,
    subscriptionPlan: "PRO" as const,
    profileViews: 640,
    portfolioViews: 1500,
  },
  {
    id: "ph-rahul-menon",
    slug: "rahul-menon",
    category: "Photographers" as const,
    name: "Rahul Menon",
    profilePhoto:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1511578314322-379afb476865?w=1400&q=80",
    location: "Bengaluru",
    bio: "Corporate and premium private event photographer with a clean, editorial eye.",
    experience: "Covers conferences, launches and upscale private celebrations across South India.",
    yearsOfExperience: 10,
    specializations: ["Corporate", "Editorial", "Event Reportage"],
    eventTypes: ["Corporate", "Custom Event", "Engagement"],
    portfolio: portfolioPool.map((url, i) => ({
      url,
      caption: `Corp ${i + 1}`,
      eventType: "Corporate",
      order: i,
    })),
    startingPrice: 25000,
    languages: ["English", "Hindi", "Kannada"],
    serviceLocations: ["Bengaluru", "Mysuru", "Hyderabad"],
    availability: "Available",
    packages: [
      {
        name: "Corporate Half Day",
        price: 25000,
        hours: 4,
        description: "Professional coverage for meetings and launches.",
        includes: ["1 photographer", "Rapid turnaround", "Brand-safe edits"],
      },
    ],
    rating: 4.6,
    reviewCount: 35,
    socialLinks: { website: "https://example.com" },
    verified: true,
    featured: true,
    status: "APPROVED" as const,
    subscriptionPlan: "PREMIUM" as const,
    profileViews: 1520,
    portfolioViews: 4100,
  },
  {
    id: "ph-sarah-thomas",
    slug: "sarah-thomas",
    category: "Photographers" as const,
    name: "Sarah Thomas",
    profilePhoto:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=1400&q=80",
    location: "Trivandrum",
    bio: "Romantic proposal and anniversary specialist creating cinematic couple moments.",
    experience: "Known for surprise-friendly setups and golden-hour couple sessions.",
    yearsOfExperience: 7,
    specializations: ["Couples", "Proposals", "Cinematic Portraits"],
    eventTypes: ["Proposal", "Anniversary", "Engagement"],
    portfolio: portfolioPool.slice(0, 6).map((url, i) => ({
      url,
      caption: `Romantic ${i + 1}`,
      eventType: "Proposal",
      order: i,
    })),
    startingPrice: 15000,
    languages: ["English", "Malayalam"],
    serviceLocations: ["Trivandrum", "Kollam", "Kovalam"],
    availability: "Available",
    packages: [
      {
        name: "Proposal Magic",
        price: 15000,
        hours: 3,
        description: "Discreet coverage of proposal and mini portrait session.",
        includes: ["1 photographer", "Hidden camera setup", "50 edits"],
      },
    ],
    rating: 4.9,
    reviewCount: 31,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: true,
    status: "APPROVED" as const,
    subscriptionPlan: "PRO" as const,
    profileViews: 1100,
    portfolioViews: 2900,
  },
  {
    id: "ph-dev-krishnan",
    slug: "dev-krishnan",
    category: "Photographers" as const,
    name: "Dev Krishnan",
    profilePhoto:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=1400&q=80",
    location: "Mysuru",
    bio: "Creative themed-party photographer who loves bold colours, props and playful storytelling.",
    experience: "Covers themed birthdays, graduation parties and creative private events.",
    yearsOfExperience: 4,
    specializations: ["Themed Events", "Creative Portraits", "Colour Grading"],
    eventTypes: ["Themed Party", "Birthday", "Graduation", "Kids Party"],
    portfolio: portfolioPool.slice(3, 10).map((url, i) => ({
      url,
      caption: `Theme ${i + 1}`,
      eventType: "Themed Party",
      order: i,
    })),
    startingPrice: 9000,
    languages: ["English", "Kannada", "Hindi"],
    serviceLocations: ["Mysuru", "Bengaluru", "Mandya"],
    availability: "Available",
    packages: [
      {
        name: "Theme Pop",
        price: 9000,
        hours: 3,
        description: "Fun, colourful coverage for themed celebrations.",
        includes: ["1 photographer", "Creative edits", "Online gallery"],
      },
    ],
    rating: 4.5,
    reviewCount: 14,
    socialLinks: { instagram: "https://instagram.com" },
    verified: false,
    featured: false,
    status: "APPROVED" as const,
    subscriptionPlan: "FREE" as const,
    profileViews: 320,
    portfolioViews: 780,
  },
  {
    id: "ph-nisha-fernandes",
    slug: "nisha-fernandes",
    name: "Nisha Fernandes",
    profilePhoto:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=1400&q=80",
    location: "Mangalore",
    bio: "Warm engagement and wedding photographer blending classic portraits with candid storytelling.",
    experience: "8+ years covering coastal weddings and multi-day family functions.",
    yearsOfExperience: 9,
    specializations: ["Wedding", "Portraits", "Multi-day Events"],
    eventTypes: ["Wedding", "Engagement", "Family Function"],
    portfolio: portfolioPool.slice(0, 9).map((url, i) => ({
      url,
      caption: `Wedding ${i + 1}`,
      eventType: "Wedding",
      order: i,
    })),
    startingPrice: 22000,
    languages: ["English", "Konkani", "Kannada", "Hindi"],
    serviceLocations: ["Mangalore", "Udupi", "Goa"],
    availability: "Booked",
    packages: [
      {
        name: "Wedding Day",
        price: 45000,
        hours: 10,
        description: "Full wedding day coverage with second shooter.",
        includes: ["2 photographers", "400+ edits", "Teaser film add-on"],
      },
    ],
    rating: 4.9,
    reviewCount: 51,
    socialLinks: { instagram: "https://instagram.com", facebook: "https://facebook.com" },
    verified: true,
    featured: true,
    status: "APPROVED" as const,
    subscriptionPlan: "PREMIUM" as const,
    profileViews: 2100,
    portfolioViews: 5200,
  },
  {
    id: "ph-vikram-singh",
    slug: "vikram-singh",
    name: "Vikram Singh",
    profilePhoto:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=1400&q=80",
    location: "Hyderabad",
    bio: "High-energy celebration photographer for birthdays, receptions and grand private parties.",
    experience: "Experienced with large guest counts and fast-paced reception floors.",
    yearsOfExperience: 11,
    specializations: ["Receptions", "Large Events", "Flash Photography"],
    eventTypes: ["Birthday", "Wedding", "Corporate", "Custom Event"],
    portfolio: portfolioPool.map((url, i) => ({
      url,
      caption: `Energy ${i + 1}`,
      eventType: "Birthday",
      order: i,
    })),
    startingPrice: 20000,
    languages: ["English", "Hindi", "Telugu"],
    serviceLocations: ["Hyderabad", "Secunderabad", "Warangal"],
    availability: "Available",
    packages: [
      {
        name: "Grand Night",
        price: 28000,
        hours: 6,
        description: "Reception and party floor coverage.",
        includes: ["1 photographer", "Flash kit", "Quick previews"],
      },
    ],
    rating: 4.4,
    reviewCount: 33,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: false,
    status: "APPROVED" as const,
    subscriptionPlan: "PRO" as const,
    profileViews: 760,
    portfolioViews: 1900,
  },
  {
    id: "ph-aisha-rahman",
    slug: "aisha-rahman",
    name: "Aisha Rahman",
    profilePhoto:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=1400&q=80",
    location: "Chennai",
    bio: "Minimal, modern aesthetic for intimate engagements and stylish private celebrations.",
    experience: "Focuses on refined compositions and contemporary couple storytelling.",
    yearsOfExperience: 5,
    specializations: ["Minimal", "Modern Couples", "Editorial"],
    eventTypes: ["Engagement", "Anniversary", "Proposal", "Custom Event"],
    portfolio: portfolioPool.slice(1, 8).map((url, i) => ({
      url,
      caption: `Modern ${i + 1}`,
      eventType: "Engagement",
      order: i,
    })),
    startingPrice: 16000,
    languages: ["English", "Tamil", "Hindi"],
    serviceLocations: ["Chennai", "Mahabalipuram", "Pondicherry"],
    availability: "Available",
    packages: [
      {
        name: "Modern Love",
        price: 16000,
        hours: 3,
        description: "Styled engagement and anniversary sessions.",
        includes: ["1 photographer", "Curated edits", "Print-ready files"],
      },
    ],
    rating: 4.8,
    reviewCount: 17,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: false,
    status: "APPROVED" as const,
    subscriptionPlan: "PRO" as const,
    profileViews: 540,
    portfolioViews: 1200,
  },
  {
    id: "ph-leo-mathew",
    slug: "leo-mathew",
    name: "Leo Mathew",
    profilePhoto:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=1400&q=80",
    location: "Kalpetta, Wayanad",
    bio: "Local Wayanad photographer capturing family functions, birthdays and destination micro-events in the hills.",
    experience: "Deep local knowledge of venues and lighting across Wayanad.",
    yearsOfExperience: 3,
    specializations: ["Destination", "Family", "Outdoor"],
    eventTypes: ["Birthday", "Family Function", "Surprise", "Custom Event"],
    portfolio: portfolioPool.slice(2, 8).map((url, i) => ({
      url,
      caption: `Wayanad ${i + 1}`,
      eventType: "Family Function",
      order: i,
    })),
    startingPrice: 8000,
    languages: ["English", "Malayalam"],
    serviceLocations: ["Kalpetta", "Sulthan Bathery", "Mananthavady"],
    availability: "Available",
    packages: [
      {
        name: "Hills & Home",
        price: 8000,
        hours: 3,
        description: "Affordable local coverage for family celebrations.",
        includes: ["1 photographer", "80 edits", "WhatsApp delivery"],
      },
    ],
    rating: 4.6,
    reviewCount: 11,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: false,
    status: "APPROVED" as const,
    subscriptionPlan: "FREE" as const,
    profileViews: 410,
    portfolioViews: 900,
  },
];

export const DEMO_HAMPERS = [
  {
    id: "hm-bloom-box",
    slug: "bloom-box-gifting",
    category: "Hamper Makers" as const,
    name: "Bloom & Box Artisanal Hampers",
    profilePhoto:
      "https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=1400&q=80",
    location: "Kochi, Kerala",
    bio: "Bespoke luxury hampers and curated gift boxes for weddings, corporate galas, and milestone birthdays.",
    experience: "Designed over 1,500+ custom hampers across Kerala and South India with premium artisan sweets and keepsakes.",
    yearsOfExperience: 6,
    specializations: ["Gourmet Treats", "Custom Keepsakes", "Luxury Packaging", "Eco-friendly"],
    eventTypes: ["Wedding", "Corporate", "Birthday", "Baby Shower"],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&q=80", caption: "Bridal Welcome Box", eventType: "Wedding", order: 0 },
      { url: "https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=800&q=80", caption: "Festive Gourmet Basket", eventType: "Corporate", order: 1 },
      { url: "https://images.unsplash.com/photo-1512909006721-3d6018887383?w=800&q=80", caption: "Organic Honey & Tea Caddy", eventType: "Custom Event", order: 2 },
    ],
    startingPrice: 3500,
    languages: ["English", "Malayalam"],
    serviceLocations: ["Kochi", "Wayanad", "Kozhikode", "Bengaluru", "Chennai"],
    availability: "Available",
    packages: [
      {
        name: "Classic Celebration Box",
        price: 3500,
        description: "Customized box with artisan chocolates, scented candle, and personalized note.",
        includes: ["Artisan Sweets", "Customized Card", "Scented Candle", "Ribbon Wrap"],
      },
      {
        name: "Luxury Royal Hamper",
        price: 8500,
        description: "Wooden trunk hamper with dry fruits, gourmet honey, engraved brass keepsakes.",
        includes: ["Wooden Keepsake Chest", "Gourmet Honey & Nuts", "Custom Brass Keepsake", "Free Delivery"],
      },
    ],
    rating: 4.9,
    reviewCount: 56,
    socialLinks: { instagram: "https://instagram.com", website: "https://bloomboxgifting.com" },
    verified: true,
    featured: true,
    status: "APPROVED" as const,
    subscriptionPlan: "PREMIUM" as const,
    profileViews: 2100,
    portfolioViews: 5400,
  },
  {
    id: "hm-soulcraft",
    slug: "soulcraft-gifting",
    category: "Hamper Makers" as const,
    name: "SoulCraft Gifting Studio",
    profilePhoto:
      "https://images.unsplash.com/photo-1544717305-2782549b5136?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1512909006721-3d6018887383?w=1400&q=80",
    location: "Wayanad, Kerala",
    bio: "Handcrafted eco-friendly return gifts, bamboo hampers, and traditional spice gifting boxes.",
    experience: "Specializing in authentic Wayanad artisan crafts, organic spices, and wedding favors.",
    yearsOfExperience: 4,
    specializations: ["Wedding Return Gifts", "Handcrafted Items", "Organic Spices", "Custom Monograms"],
    eventTypes: ["Wedding", "Engagement", "Family Function"],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1512909006721-3d6018887383?w=800&q=80", caption: "Wayanad Spice Trunk", eventType: "Wedding", order: 0 },
      { url: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&q=80", caption: "Bamboo Favor Basket", eventType: "Family Function", order: 1 },
    ],
    startingPrice: 2000,
    languages: ["English", "Malayalam"],
    serviceLocations: ["Wayanad", "Kalpetta", "Sulthan Bathery", "Mananthavady", "Kozhikode", "Kannur"],
    availability: "Available",
    packages: [
      {
        name: "Eco Spice Favor Box",
        price: 2000,
        description: "Jute hamper filled with organic tea, cardamom & handmade soap.",
        includes: ["Organic Wayanad Tea", "Cardamom & Spices", "Jute Basket Packaging"],
      },
    ],
    rating: 4.8,
    reviewCount: 38,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: true,
    status: "APPROVED" as const,
    subscriptionPlan: "PRO" as const,
    profileViews: 1450,
    portfolioViews: 3200,
  },
  {
    id: "hm-royal-blossom",
    slug: "royal-blossom-hampers",
    category: "Hamper Makers" as const,
    name: "Royal Blossom Luxe Hampers",
    profilePhoto:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=1400&q=80",
    location: "Bengaluru, Karnataka",
    bio: "Premium curated gift boxes for wedding invitations, baby arrival hampers and corporate client gestures.",
    experience: "5+ years crafting luxury velvet and brass gift boxes across Bengaluru, Mysuru & Coimbatore.",
    yearsOfExperience: 5,
    specializations: ["Invitation Hampers", "Baby Arrival Trunks", "Brass & Velvet Trays", "Custom Sweets"],
    eventTypes: ["Wedding", "Baby Shower", "Corporate"],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=800&q=80", caption: "Velvet Baby Arrival Trunk", eventType: "Baby Shower", order: 0 },
    ],
    startingPrice: 4500,
    languages: ["English", "Kannada", "Hindi"],
    serviceLocations: ["Bengaluru", "Mysuru", "Coimbatore", "Chennai", "Kochi"],
    availability: "Available",
    packages: [
      {
        name: "Velvet Deluxe Trunk",
        price: 4500,
        description: "Monogrammed velvet trunk with dried fruits, scented wax tablets, and brass candle holder.",
        includes: ["Velvet Trunk", "Gourmet Dry Fruits", "Custom Monogram", "Wax Tablets"],
      },
    ],
    rating: 4.9,
    reviewCount: 29,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: false,
    status: "APPROVED" as const,
    subscriptionPlan: "PRO" as const,
    profileViews: 1120,
    portfolioViews: 2800,
  },
];

export const DEMO_HENNA_DESIGNERS = [
  {
    id: "hn-zara-mehendi",
    slug: "zara-mehendi-artistry",
    category: "Henna Artists" as const,
    name: "Zara Mehendi Artistry",
    profilePhoto:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1600091166971-7f9faad6c1e2?w=1400&q=80",
    location: "Kozhikode, Kerala",
    bio: "Exquisite bridal henna specialist creating rich stain organic Mehendi with intricate portraits & royal Arabic motifs.",
    experience: "over 10+ years crafting dream bridal henna for destination weddings in Kerala, Dubai & Karnataka.",
    yearsOfExperience: 10,
    specializations: ["Organic Mehendi", "Bridal Figures", "Intricate Arabic", "Modern Motif"],
    eventTypes: ["Wedding", "Engagement", "Baby Shower", "Custom Event"],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1600091166971-7f9faad6c1e2?w=800&q=80", caption: "Full Arm Bridal Henna", eventType: "Wedding", order: 0 },
      { url: "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80", caption: "Arabic Minimalist Feet", eventType: "Engagement", order: 1 },
    ],
    startingPrice: 5000,
    languages: ["English", "Malayalam", "Hindi"],
    serviceLocations: ["Kozhikode", "Wayanad", "Kalpetta", "Kochi", "Malappuram", "Kannur"],
    availability: "Available",
    packages: [
      {
        name: "Bridal Royal Package",
        price: 12000,
        description: "Full hand front & back till elbow + feet mehendi with guaranteed dark stain organic cones.",
        includes: ["100% Organic Henna Cones", "Bride Story Motif", "Feet Henna", "Aftercare Sealant Oil"],
      },
      {
        name: "Party & Guest Mehendi",
        price: 5000,
        description: "Side coverage for up to 5 family members/guests.",
        includes: ["5 Guest Hands", "Quick Dry Cones", "Custom Arabic Designs"],
      },
    ],
    rating: 4.9,
    reviewCount: 64,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: true,
    status: "APPROVED" as const,
    subscriptionPlan: "PREMIUM" as const,
    profileViews: 3100,
    portfolioViews: 7800,
  },
  {
    id: "hn-aiswarya-bridal",
    slug: "aiswarya-bridal-henna",
    category: "Henna Artists" as const,
    name: "Aiswarya Bridal Henna",
    profilePhoto:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=1400&q=80",
    location: "Wayanad, Kerala",
    bio: "Traditional Kerala & Rajasthani fusion Mehendi artist known for symmetrical delicacy and fast application.",
    experience: "Trusted by hundreds of brides in Wayanad and Malabar region for spotless traditional henna patterns.",
    yearsOfExperience: 7,
    specializations: ["Traditional Kerala Pattern", "Rajasthani Bridal", "Guest Packages", "Stain Guarantee"],
    eventTypes: ["Wedding", "Engagement", "Family Function"],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=800&q=80", caption: "Symmetrical Bridal Palms", eventType: "Wedding", order: 0 },
    ],
    startingPrice: 4000,
    languages: ["English", "Malayalam"],
    serviceLocations: ["Wayanad", "Kalpetta", "Mananthavady", "Sulthan Bathery", "Palakkad"],
    availability: "Available",
    packages: [
      {
        name: "Standard Bridal Mehendi",
        price: 8000,
        description: "Elbow-length bridal henna with traditional peacock and floral elements.",
        includes: ["Both Hands till Elbow", "Ankle Feet Coverage", "Natural Eucalyptus Aftercare"],
      },
    ],
    rating: 4.8,
    reviewCount: 41,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: true,
    status: "APPROVED" as const,
    subscriptionPlan: "PRO" as const,
    profileViews: 1890,
    portfolioViews: 4100,
  },
  {
    id: "hn-noor-studio",
    slug: "noor-henna-studio",
    category: "Henna Artists" as const,
    name: "Noor Henna Artistry",
    profilePhoto:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1600091166971-7f9faad6c1e2?w=1400&q=80",
    location: "Chennai, Tamil Nadu",
    bio: "Contemporary Indo-Arabic & geometric mandala henna artist for brides and festive parties.",
    experience: "8+ years covering high-profile NRI weddings and destination mehendi events.",
    yearsOfExperience: 8,
    specializations: ["Indo-Arabic", "Mandala Palms", "Stain Oil Sealant", "Speed Application"],
    eventTypes: ["Wedding", "Engagement", "Party"],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1600091166971-7f9faad6c1e2?w=800&q=80", caption: "Mandala Palm Henna", eventType: "Engagement", order: 0 },
    ],
    startingPrice: 4500,
    languages: ["English", "Tamil", "Hindi"],
    serviceLocations: ["Chennai", "Coimbatore", "Bengaluru", "Kochi"],
    availability: "Available",
    packages: [
      {
        name: "Mandala Bridal Special",
        price: 9500,
        description: "Both hands up to mid-forearm with intricate central mandala & lotus tips.",
        includes: ["Organic Cones", "Mid-forearm Coverage", "Aftercare Balm"],
      },
    ],
    rating: 4.9,
    reviewCount: 35,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: false,
    status: "APPROVED" as const,
    subscriptionPlan: "PRO" as const,
    profileViews: 1650,
    portfolioViews: 3800,
  },
];

export const DEMO_MAKEUP_ARTISTS = [
  {
    id: "mk-glamour-diya",
    slug: "glamour-grace-diya",
    category: "Makeup Artists" as const,
    name: "Glamour & Grace by Diya",
    profilePhoto:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=1400&q=80",
    location: "Kochi, Kerala",
    bio: "Celebrity bridal makeup artist specializing in HD Airbrush makeup, glass-skin glowing finishes and elegant hair styling.",
    experience: "12+ years in fashion & luxury bridal makeovers across South India.",
    yearsOfExperience: 12,
    specializations: ["HD Bridal Makeup", "Airbrush Technique", "South Indian Traditional", "Glass Skin Glow"],
    eventTypes: ["Wedding", "Engagement", "Reception", "Corporate"],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=800&q=80", caption: "Traditional Bride Makeover", eventType: "Wedding", order: 0 },
      { url: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80", caption: "Reception Evening Glam", eventType: "Reception", order: 1 },
    ],
    startingPrice: 12000,
    languages: ["English", "Malayalam", "Tamil", "Hindi"],
    serviceLocations: ["Kochi", "Wayanad", "Kalpetta", "Kozhikode", "Trivandrum", "Bengaluru", "Chennai"],
    availability: "Available",
    packages: [
      {
        name: "HD Bridal Transformation",
        price: 22000,
        description: "HD water-resistant makeup, premium mink lashes, hair styling, jewelry setting & saree draping.",
        includes: ["HD Makeup", "Lashes & Lenses", "Bridal Hair Styling", "Saree / Lehenga Draping", "Touchup Kit"],
      },
      {
        name: "Engagement / Party Glam",
        price: 12000,
        description: "Lightweight long-lasting glam for engagements or cocktail nights.",
        includes: ["Soft Glam Makeup", "Hair Styling", "Draping Assistance"],
      },
    ],
    rating: 4.9,
    reviewCount: 78,
    socialLinks: { instagram: "https://instagram.com", youtube: "https://youtube.com" },
    verified: true,
    featured: true,
    status: "APPROVED" as const,
    subscriptionPlan: "PREMIUM" as const,
    profileViews: 4200,
    portfolioViews: 9500,
  },
  {
    id: "mk-luxe-glow",
    slug: "luxe-glow-studio",
    category: "Makeup Artists" as const,
    name: "Luxe Glow Makeup Studio",
    profilePhoto:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=1400&q=80",
    location: "Kozhikode, Kerala",
    bio: "Contemporary makeup studio focused on enhancing natural features with flawless dewy skin & bespoke hairstyling.",
    experience: "Worked with 400+ brides in North Kerala with a focus on comfortable, long-wearing bridal looks.",
    yearsOfExperience: 6,
    specializations: ["Dewy Glow Finish", "Engagement Glam", "Hairstyling & Draping", "Monochrome Tones"],
    eventTypes: ["Wedding", "Engagement", "Birthday", "Party"],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80", caption: "Dewy Nude Engagement Look", eventType: "Engagement", order: 0 },
    ],
    startingPrice: 10000,
    languages: ["English", "Malayalam"],
    serviceLocations: ["Kozhikode", "Wayanad", "Kalpetta", "Sulthan Bathery", "Malappuram", "Kannur"],
    availability: "Available",
    packages: [
      {
        name: "Signature Dewy Makeup",
        price: 16000,
        description: "Dewy finish bridal makeup with custom hair extensions and accessories placement.",
        includes: ["Signature Glow Makeup", "Hair Styling", "Lash Extensions", "Draping"],
      },
    ],
    rating: 4.8,
    reviewCount: 45,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: true,
    status: "APPROVED" as const,
    subscriptionPlan: "PRO" as const,
    profileViews: 2300,
    portfolioViews: 5100,
  },
  {
    id: "mk-reshma-touch",
    slug: "reshma-touch-makeovers",
    category: "Makeup Artists" as const,
    name: "Reshma Touch Makeovers",
    profilePhoto:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=1400&q=80",
    location: "Coimbatore, Tamil Nadu",
    bio: "Bridal makeover expert specializing in classic South Indian silk saree look, temple jewelry setting & airbrush finish.",
    experience: "7+ years crafting stunning bridal transformations across Coimbatore, Mysuru & Palakkad.",
    yearsOfExperience: 7,
    specializations: ["South Indian Silk Bride", "Temple Jewelry Setting", "Airbrush Finish", "Kathan Weave Draping"],
    eventTypes: ["Wedding", "Reception", "Engagement"],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=800&q=80", caption: "Coimbatore Traditional Bride", eventType: "Wedding", order: 0 },
    ],
    startingPrice: 11000,
    languages: ["English", "Tamil", "Malayalam"],
    serviceLocations: ["Coimbatore", "Palakkad", "Mysuru", "Bengaluru", "Kochi"],
    availability: "Available",
    packages: [
      {
        name: "Classic Silk Bride Makeover",
        price: 18000,
        description: "Waterproof long-stay makeup, traditional floral braid, saree pleating & jewelry pin-up.",
        includes: ["Airbrush Makeup", "Floral Braid Styling", "Saree Pleating & Setting"],
      },
    ],
    rating: 4.9,
    reviewCount: 39,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: false,
    status: "APPROVED" as const,
    subscriptionPlan: "PRO" as const,
    profileViews: 1780,
    portfolioViews: 3900,
  },
];

export const DEMO_CAKE_BAKERS = [
  {
    id: "ck-velvet-crumbs",
    slug: "velvet-crumbs-bakehouse",
    category: "Cake Bakers" as const,
    name: "Velvet & Crumbs Artisan Bakehouse",
    profilePhoto:
      "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=1400&q=80",
    location: "Kochi, Kerala",
    bio: "Bespoke multi-tier wedding cakes, hand-sculpted sugar flowers, fondant art, and elaborate dessert tables.",
    experience: "Crafted over 800+ tier cakes for luxury weddings & grand birthdays across South India.",
    yearsOfExperience: 7,
    specializations: ["Multi-tier Wedding Cakes", "Sugar Flowers", "Dessert Tables", "Eggless Options"],
    eventTypes: ["Wedding", "Birthday", "Anniversary", "Baby Shower"],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=800&q=80", caption: "4-Tier Floral Wedding Cake", eventType: "Wedding", order: 0 },
      { url: "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=800&q=80", caption: "Naked Berry Birthday Cake", eventType: "Birthday", order: 1 },
    ],
    startingPrice: 4500,
    languages: ["English", "Malayalam"],
    serviceLocations: ["Kochi", "Wayanad", "Kalpetta", "Kozhikode", "Bengaluru"],
    availability: "Available",
    packages: [
      {
        name: "3-Tier Floral Wedding Cake",
        price: 14000,
        description: "Custom flavored 3-tier wedding cake decorated with handcrafted sugar roses and gold leafing.",
        includes: ["3 Tiers (6kg+)", "Hand-crafted Sugar Flowers", "Refrigerated Van Delivery", "Cake Tasting Box"],
      },
      {
        name: "Theme Birthday Cake & Cupcakes",
        price: 4500,
        description: "2kg custom themed birthday cake with 12 matching cupcakes.",
        includes: ["2kg Custom Cake", "12 Theme Cupcakes", "Candles & Box Packaging"],
      },
    ],
    rating: 4.9,
    reviewCount: 62,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: true,
    status: "APPROVED" as const,
    subscriptionPlan: "PREMIUM" as const,
    profileViews: 2800,
    portfolioViews: 6400,
  },
  {
    id: "ck-sugar-spice",
    slug: "sugar-spice-cakes",
    category: "Cake Bakers" as const,
    name: "Sugar & Spice Custom Cakes",
    profilePhoto:
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=1400&q=80",
    location: "Kalpetta, Wayanad",
    bio: "Home-style artisanal cake studio specializing in fresh cream florals, bento cakes, and kids theme cakes in Wayanad.",
    experience: "Local favorite for birthday and anniversary surprise cakes with pure butter and premium chocolates.",
    yearsOfExperience: 5,
    specializations: ["Fresh Cream Florals", "Kids Theme Cakes", "Bento Surprise Boxes", "Belgium Chocolate"],
    eventTypes: ["Birthday", "Kids Party", "Anniversary", "Surprise Party"],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&q=80", caption: "Custom Chocolate Drip Cake", eventType: "Birthday", order: 0 },
    ],
    startingPrice: 1800,
    languages: ["English", "Malayalam"],
    serviceLocations: ["Kalpetta", "Wayanad", "Sulthan Bathery", "Mananthavady", "Kozhikode"],
    availability: "Available",
    packages: [
      {
        name: "Celebration Special Cake (2kg)",
        price: 2400,
        description: "Belgian truffle or fresh mango cake with personalized toppers and candles.",
        includes: ["2kg Premium Cake", "Custom Cake Topper", "Free Doorstep Delivery in Kalpetta"],
      },
    ],
    rating: 4.8,
    reviewCount: 47,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: true,
    status: "APPROVED" as const,
    subscriptionPlan: "PRO" as const,
    profileViews: 1950,
    portfolioViews: 4300,
  },
  {
    id: "ck-royal-patisserie",
    slug: "royal-patisserie-bakers",
    category: "Cake Bakers" as const,
    name: "The Royal Patisserie & Desserts",
    profilePhoto:
      "https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=1400&q=80",
    location: "Bengaluru, Karnataka",
    bio: "French patisserie & luxury cake house offering macaron towers, dessert tables, and grand celebration cakes.",
    experience: "Partnered with luxury event planners across Bengaluru, Mysuru, Chennai & Kochi.",
    yearsOfExperience: 8,
    specializations: ["French Desserts", "Macaron Towers", "Grand Wedding Cakes", "Gourmet Flavors"],
    eventTypes: ["Wedding", "Corporate", "Anniversary"],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=800&q=80", caption: "French Macaron Wedding Tower", eventType: "Wedding", order: 0 },
    ],
    startingPrice: 5000,
    languages: ["English", "Kannada", "Hindi"],
    serviceLocations: ["Bengaluru", "Mysuru", "Chennai", "Coimbatore", "Kochi"],
    availability: "Available",
    packages: [
      {
        name: "Grand Dessert Bar & Cake",
        price: 25000,
        description: "Full dessert bar with mini tarts, eclairs, macarons, and a 2-tier centerpiece cake.",
        includes: ["2-Tier Centerpiece Cake", "50 Macarons", "40 Mini Tarts & Shooters", "Setup & Display Trays"],
      },
    ],
    rating: 4.9,
    reviewCount: 54,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: false,
    status: "APPROVED" as const,
    subscriptionPlan: "PREMIUM" as const,
    profileViews: 2400,
    portfolioViews: 5800,
  },
];

export const DEMO_CREATIVES = [
  ...DEMO_PHOTOGRAPHERS.slice(0, 3).map((p) => ({ ...p, category: "Photographers" as const })),
  ...DEMO_HENNA_DESIGNERS.slice(0, 3),
  ...DEMO_MAKEUP_ARTISTS.slice(0, 3),
  ...DEMO_HAMPERS.slice(0, 3),
  ...DEMO_CAKE_BAKERS.slice(0, 3),
];

export const DEMO_REVIEWS = [
  {
    id: "rev-1",
    name: "Priya Menon",
    avatar:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80",
    rating: 5,
    review:
      "ShapeMyMoment handled our anniversary from décor to photography. We actually enjoyed the evening instead of managing vendors.",
    eventType: "Anniversary" as const,
    photographerId: "ph-ananya-rao",
    packageId: "pkg-intimate-romance",
    status: "APPROVED" as const,
    featured: true,
    date: "2025-11-12",
  },
  {
    id: "rev-2",
    name: "Rohit Sharma",
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    rating: 5,
    review:
      "Our daughter's birthday was stress-free. The team coordinated cake, décor and photos perfectly within budget.",
    eventType: "Birthday" as const,
    photographerId: "ph-arjun-nair",
    packageId: "pkg-birthday-essentials",
    status: "APPROVED" as const,
    featured: true,
    date: "2025-12-03",
  },
  {
    id: "rev-3",
    name: "Anjali Nair",
    rating: 5,
    review:
      "The surprise proposal setup was magical. Discreet coordination and beautiful photography — she said yes!",
    eventType: "Proposal" as const,
    photographerId: "ph-sarah-thomas",
    packageId: "pkg-intimate-romance",
    status: "APPROVED" as const,
    featured: true,
    date: "2026-01-18",
  },
  {
    id: "rev-4",
    name: "Farah Khan",
    rating: 4,
    review:
      "Baby shower styling was soft and elegant. Guests kept asking who planned it.",
    eventType: "Baby Shower" as const,
    photographerId: "ph-meera-joseph",
    packageId: "pkg-baby-bloom",
    status: "APPROVED" as const,
    featured: false,
    date: "2026-02-02",
  },
  {
    id: "rev-5",
    name: "Sandeep Kumar",
    rating: 5,
    review:
      "Corporate offsite looked polished. Clear communication and on-time execution throughout.",
    eventType: "Corporate" as const,
    photographerId: "ph-rahul-menon",
    packageId: "pkg-corporate-gather",
    status: "APPROVED" as const,
    featured: true,
    date: "2026-02-20",
  },
  {
    id: "rev-6",
    name: "Lakshmi R",
    rating: 5,
    review:
      "Wedding planning felt like having a trusted partner. Every detail was handled with care.",
    eventType: "Wedding" as const,
    photographerId: "ph-nisha-fernandes",
    packageId: "pkg-signature",
    status: "APPROVED" as const,
    featured: true,
    date: "2026-03-08",
  },
  {
    id: "rev-7",
    name: "Imran Ali",
    rating: 4,
    review:
      "Kids party was chaotic in the best way — and we didn't have to manage any of it.",
    eventType: "Kids Party" as const,
    photographerId: "ph-dev-krishnan",
    packageId: "pkg-kids-magic",
    status: "APPROVED" as const,
    featured: false,
    date: "2026-03-22",
  },
  {
    id: "rev-8",
    name: "Neha Patel",
    rating: 5,
    review:
      "Transparent planning and beautiful final result. Celebration Plus was worth every rupee.",
    eventType: "Engagement" as const,
    packageId: "pkg-celebration-plus",
    status: "APPROVED" as const,
    featured: true,
    date: "2026-04-01",
  },
  {
    id: "rev-9",
    name: "Jose Thomas",
    rating: 5,
    review:
      "Local Wayanad coverage was excellent. Leo knew the perfect spots for family photos.",
    eventType: "Family Function" as const,
    photographerId: "ph-leo-mathew",
    status: "APPROVED" as const,
    featured: false,
    date: "2026-04-15",
  },
  {
    id: "rev-10",
    name: "Divya Krishnan",
    rating: 5,
    review:
      "From first call to final celebration, ShapeMyMoment made everything effortless.",
    eventType: "Custom Event" as const,
    packageId: "pkg-signature",
    status: "APPROVED" as const,
    featured: true,
    date: "2026-05-10",
  },
] as const;

export const DEMO_FAQS = [
  {
    question: "What does ShapeMyMoment actually handle?",
    answer:
      "We plan, source, arrange, coordinate and manage your event end-to-end — décor, vendors, photography, catering coordination and on-day execution based on your brief and budget.",
  },
  {
    question: "How does custom event planning work?",
    answer:
      "Share your vision through Plan My Event. Our team reviews your date, location, guest count, budget and required services, then builds a customized package and quotation.",
  },
  {
    question: "Can I only book a photographer?",
    answer:
      "Yes. Browse our photographer directory, view portfolios and request a photographer directly — or include photography as part of a full event package.",
  },
  {
    question: "How far in advance should I book?",
    answer:
      "We recommend 3–6 weeks for most celebrations and longer for weddings or peak dates. Surprise events can often be arranged faster depending on availability.",
  },
  {
    question: "Do you work within a fixed budget?",
    answer:
      "Absolutely. Tell us your budget upfront and we design a realistic plan — prioritizing what matters most to you.",
  },
  {
    question: "Where do you currently operate?",
    answer:
      "We primarily serve Wayanad, Kozhikode and nearby Kerala locations, with selective coverage across South India for premium packages.",
  },
] as const;

export const DEMO_EVENT_REQUESTS = [
  {
    id: "er-1",
    requestId: "SMM-260901-A1B2C3",
    eventType: "Birthday",
    eventDate: "2026-10-20",
    location: "Kalpetta",
    expectedGuests: 30,
    budget: 50000,
    duration: "4 hours",
    services: ["Decoration", "Photography", "Cake", "Entertainment"],
    vision: "Luxury pink theme kids birthday with soft décor and candid photos.",
    theme: "Luxury Pink",
    name: "Anitha R",
    email: "anitha@example.com",
    phone: "9876543210",
    whatsapp: "9876543210",
    preferredContact: "WhatsApp",
    status: "NEW",
    createdAt: "2026-09-01T10:00:00.000Z",
  },
  {
    id: "er-2",
    requestId: "SMM-260828-D4E5F6",
    eventType: "Anniversary",
    eventDate: "2026-09-28",
    location: "Kochi",
    expectedGuests: 20,
    budget: 35000,
    duration: "3 hours",
    services: ["Decoration", "Photography", "Music", "Event Coordination"],
    vision: "Intimate 10th anniversary dinner with romantic décor.",
    name: "Vivek S",
    email: "vivek@example.com",
    phone: "9988776655",
    preferredContact: "Phone",
    status: "PLANNING",
    createdAt: "2026-08-28T14:20:00.000Z",
  },
] as const;
