export const DEMO_EVENT_TYPES = [
  {
    name: "Birthday",
    slug: "birthday",
    description: "Memorable birthday celebrations tailored to every age and style.",
    image:
      "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=80",
  },
  {
    name: "Wedding",
    slug: "wedding",
    description: "Elegant wedding planning from engagement to the big day.",
    image:
      "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80",
  },
  {
    name: "Engagement",
    slug: "engagement",
    description: "Intimate and grand engagement celebrations done right.",
    image:
      "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=800&q=80",
  },
  {
    name: "Baby Shower",
    slug: "baby-shower",
    description: "Warm, joyful showers for the newest chapter ahead.",
    image:
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&q=80",
  },
  {
    name: "Anniversary",
    slug: "anniversary",
    description: "Romantic milestones planned with care and elegance.",
    image:
      "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800&q=80",
  },
  {
    name: "Corporate",
    slug: "corporate",
    description: "Professional events that impress teams and clients.",
    image:
      "https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&q=80",
  },
  {
    name: "Surprise Party",
    slug: "surprise-party",
    description: "Flawlessly secret surprises that land perfectly.",
    image:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80",
  },
  {
    name: "Kids Party",
    slug: "kids-party",
    description: "Fun-filled themed parties kids never forget.",
    image:
      "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=800&q=80",
  },
  {
    name: "Proposal",
    slug: "proposal",
    description: "Cinematic proposal setups for once-in-a-lifetime yeses.",
    image:
      "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=800&q=80",
  },
  {
    name: "Custom Event",
    slug: "custom-event",
    description: "Fully custom celebrations designed around your vision.",
    image:
      "https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=800&q=80",
  },
] as const;

export const DEMO_PACKAGES = [
  {
    id: "pkg-birthday-essentials",
    name: "Birthday Essentials",
    slug: "birthday-essentials",
    description:
      "A thoughtfully curated birthday package with the essentials handled — décor, cake coordination, photography and light entertainment — so you can focus on celebrating.",
    startingPrice: 15000,
    eventTypes: ["Birthday", "Kids Party", "Surprise"],
    services: ["Decoration", "Cake", "Photography", "Entertainment"],
    images: [
      "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=1000&q=80",
    ],
    highlights: [
      "Theme decoration setup",
      "Cake coordination",
      "2-hour photography",
      "Basic entertainment",
    ],
    featured: true,
    active: true,
  },
  {
    id: "pkg-celebration-plus",
    name: "Celebration Plus",
    slug: "celebration-plus",
    description:
      "A complete celebration package covering décor, photo & video, cake, entertainment and dedicated event coordination for a seamless experience.",
    startingPrice: 30000,
    eventTypes: ["Birthday", "Anniversary", "Engagement", "Baby Shower"],
    services: [
      "Decoration",
      "Photography",
      "Videography",
      "Cake",
      "Entertainment",
      "Event Coordination",
    ],
    images: [
      "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=1000&q=80",
    ],
    highlights: [
      "Premium décor styling",
      "Photo + video coverage",
      "Cake & entertainment",
      "On-day event coordinator",
    ],
    featured: true,
    active: true,
  },
  {
    id: "pkg-signature",
    name: "Signature Celebration",
    slug: "signature-celebration",
    description:
      "Our flagship end-to-end experience — premium décor, full media coverage, catering support, venue assistance and complete coordination from idea to celebration.",
    startingPrice: 60000,
    eventTypes: ["Wedding", "Engagement", "Corporate", "Custom Event"],
    services: [
      "Premium Decoration",
      "Photography",
      "Videography",
      "Catering",
      "Entertainment",
      "Venue",
      "Event Coordination",
    ],
    images: [
      "https://images.unsplash.com/photo-1519741497674-611481863552?w=1000&q=80",
    ],
    highlights: [
      "Premium décor & styling",
      "Full photo & video team",
      "Catering coordination",
      "Venue assistance",
      "Dedicated event manager",
    ],
    featured: true,
    active: true,
  },
  {
    id: "pkg-kids-magic",
    name: "Kids Magic Day",
    slug: "kids-magic-day",
    description:
      "Colourful kids parties with themed décor, games, return gifts and photography — designed for little smiles and calm parents.",
    startingPrice: 18000,
    eventTypes: ["Kids Party", "Birthday"],
    services: [
      "Decoration",
      "Entertainment",
      "Return Gifts",
      "Photography",
      "Cake",
    ],
    images: [
      "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=1000&q=80",
    ],
    highlights: [
      "Themed kids décor",
      "Games & host",
      "Return gifts",
      "Cake & photography",
    ],
    featured: false,
    active: true,
  },
  {
    id: "pkg-intimate-romance",
    name: "Intimate Romance",
    slug: "intimate-romance",
    description:
      "Elegant anniversary and proposal setups with romantic décor, photography and carefully planned surprise moments.",
    startingPrice: 25000,
    eventTypes: ["Anniversary", "Proposal", "Engagement"],
    services: ["Decoration", "Photography", "Music", "Event Coordination"],
    images: [
      "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=1000&q=80",
    ],
    highlights: [
      "Romantic décor styling",
      "Surprise moment planning",
      "Couple photography",
      "Ambient music setup",
    ],
    featured: true,
    active: true,
  },
  {
    id: "pkg-corporate-gather",
    name: "Corporate Gather",
    slug: "corporate-gather",
    description:
      "Professional corporate gatherings with venue support, AV coordination, catering and on-site management.",
    startingPrice: 45000,
    eventTypes: ["Corporate"],
    services: [
      "Venue",
      "Catering",
      "Entertainment",
      "Photography",
      "Event Coordination",
    ],
    images: [
      "https://images.unsplash.com/photo-1511578314322-379afb476865?w=1000&q=80",
    ],
    highlights: [
      "Venue & layout planning",
      "Catering coordination",
      "AV & stage support",
      "On-site event manager",
    ],
    featured: false,
    active: true,
  },
  {
    id: "pkg-surprise-night",
    name: "Surprise Night",
    slug: "surprise-night",
    description:
      "Secret-friendly surprise party planning with discreet coordination, décor, entertainment and photography.",
    startingPrice: 22000,
    eventTypes: ["Surprise", "Birthday"],
    services: [
      "Decoration",
      "Entertainment",
      "Photography",
      "Invitations",
      "Event Coordination",
    ],
    images: [
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1000&q=80",
    ],
    highlights: [
      "Discreet planning",
      "Reveal moment styling",
      "Guest coordination",
      "Photo coverage",
    ],
    featured: false,
    active: true,
  },
  {
    id: "pkg-baby-bloom",
    name: "Baby Bloom Shower",
    slug: "baby-bloom-shower",
    description:
      "Soft, stylish baby showers with décor, cake, photography and thoughtful guest experiences.",
    startingPrice: 20000,
    eventTypes: ["Baby Shower"],
    services: [
      "Decoration",
      "Cake",
      "Photography",
      "Return Gifts",
      "Event Coordination",
    ],
    images: [
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=1000&q=80",
    ],
    highlights: [
      "Soft theme décor",
      "Cake styling",
      "Guest favours",
      "Photo moments",
    ],
    featured: false,
    active: true,
  },
] as const;

const portfolioPool = [
  "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&q=80",
  "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=800&q=80",
  "https://images.unsplash.com/photo-1529636798458-92182e662485?w=800&q=80",
  "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80",
  "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&q=80",
  "https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=800&q=80",
  "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=80",
  "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80",
  "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=800&q=80",
  "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800&q=80",
];

export const DEMO_PHOTOGRAPHERS = [
  {
    id: "ph-ananya-rao",
    slug: "ananya-rao",
    name: "Ananya Rao",
    profilePhoto:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1519741497674-611481863552?w=1400&q=80",
    location: "Kalpetta, Wayanad",
    bio: "Documentary-style wedding and celebration photographer capturing emotion with soft natural light and honest moments.",
    experience:
      "Worked across Kerala weddings, destination celebrations and intimate family events with a calm, unobtrusive approach.",
    yearsOfExperience: 8,
    specializations: ["Candid", "Natural Light", "Wedding Storytelling"],
    eventTypes: ["Wedding", "Engagement", "Anniversary", "Proposal"],
    portfolio: portfolioPool.slice(0, 8).map((url, i) => ({
      url,
      caption: `Frame ${i + 1}`,
      eventType: "Wedding",
      order: i,
    })),
    startingPrice: 18000,
    languages: ["English", "Malayalam", "Hindi"],
    serviceLocations: ["Kalpetta", "Wayanad", "Kozhikode", "Kochi"],
    availability: "Available",
    packages: [
      {
        name: "Half Day Story",
        price: 18000,
        hours: 4,
        description: "Intimate coverage for proposals and small celebrations.",
        includes: ["1 photographer", "Edited gallery", "Online delivery"],
      },
      {
        name: "Celebration Day",
        price: 32000,
        hours: 8,
        description: "Full celebration coverage with highlight reel option.",
        includes: ["1 photographer", "200+ edits", "Highlight reel add-on"],
      },
    ],
    rating: 4.9,
    reviewCount: 42,
    socialLinks: { instagram: "https://instagram.com", website: "" },
    verified: true,
    featured: true,
    status: "APPROVED" as const,
    subscriptionPlan: "PREMIUM" as const,
    profileViews: 1280,
    portfolioViews: 3400,
  },
  {
    id: "ph-arjun-nair",
    slug: "arjun-nair",
    name: "Arjun Nair",
    profilePhoto:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1400&q=80",
    location: "Kozhikode",
    bio: "Vibrant event photographer specializing in birthday parties, surprise reveals and high-energy celebrations.",
    experience: "Known for dynamic lighting setups and lively party coverage across North Kerala.",
    yearsOfExperience: 6,
    specializations: ["Event Lighting", "Party Coverage", "Candid Portraits"],
    eventTypes: ["Birthday", "Surprise", "Kids Party", "Corporate"],
    portfolio: portfolioPool.slice(2, 10).map((url, i) => ({
      url,
      caption: `Party ${i + 1}`,
      eventType: "Birthday",
      order: i,
    })),
    startingPrice: 12000,
    languages: ["English", "Malayalam"],
    serviceLocations: ["Kozhikode", "Malappuram", "Wayanad"],
    availability: "Available",
    packages: [
      {
        name: "Party Essentials",
        price: 12000,
        hours: 3,
        description: "Perfect for home birthdays and intimate gatherings.",
        includes: ["1 photographer", "100 edits", "Same-week delivery"],
      },
    ],
    rating: 4.7,
    reviewCount: 28,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: true,
    status: "APPROVED" as const,
    subscriptionPlan: "PRO" as const,
    profileViews: 890,
    portfolioViews: 2100,
  },
  {
    id: "ph-meera-joseph",
    slug: "meera-joseph",
    name: "Meera Joseph",
    profilePhoto:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=1400&q=80",
    location: "Kochi",
    bio: "Soft, elegant imagery for baby showers, maternity moments and family celebrations.",
    experience: "Specializes in gentle direction and lifestyle family storytelling.",
    yearsOfExperience: 5,
    specializations: ["Lifestyle", "Family", "Baby Shower"],
    eventTypes: ["Baby Shower", "Birthday", "Family Function", "Anniversary"],
    portfolio: portfolioPool.slice(1, 9).map((url, i) => ({
      url,
      caption: `Soft ${i + 1}`,
      eventType: "Baby Shower",
      order: i,
    })),
    startingPrice: 10000,
    languages: ["English", "Malayalam", "Tamil"],
    serviceLocations: ["Kochi", "Ernakulam", "Alappuzha"],
    availability: "Limited",
    packages: [
      {
        name: "Bloom Session",
        price: 10000,
        hours: 2,
        description: "Beautiful baby shower and family coverage.",
        includes: ["1 photographer", "80 edits", "Online album"],
      },
    ],
    rating: 4.8,
    reviewCount: 19,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: false,
    status: "APPROVED" as const,
    subscriptionPlan: "PRO" as const,
    profileViews: 640,
    portfolioViews: 1500,
  },
  {
    id: "ph-rahul-menon",
    slug: "rahul-menon",
    name: "Rahul Menon",
    profilePhoto:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1511578314322-379afb476865?w=1400&q=80",
    location: "Bengaluru",
    bio: "Corporate and premium private event photographer with a clean, editorial eye.",
    experience: "Covers conferences, launches and upscale private celebrations across South India.",
    yearsOfExperience: 10,
    specializations: ["Corporate", "Editorial", "Event Reportage"],
    eventTypes: ["Corporate", "Custom Event", "Engagement"],
    portfolio: portfolioPool.map((url, i) => ({
      url,
      caption: `Corp ${i + 1}`,
      eventType: "Corporate",
      order: i,
    })),
    startingPrice: 25000,
    languages: ["English", "Hindi", "Kannada"],
    serviceLocations: ["Bengaluru", "Mysuru", "Hyderabad"],
    availability: "Available",
    packages: [
      {
        name: "Corporate Half Day",
        price: 25000,
        hours: 4,
        description: "Professional coverage for meetings and launches.",
        includes: ["1 photographer", "Rapid turnaround", "Brand-safe edits"],
      },
    ],
    rating: 4.6,
    reviewCount: 35,
    socialLinks: { website: "https://example.com" },
    verified: true,
    featured: true,
    status: "APPROVED" as const,
    subscriptionPlan: "PREMIUM" as const,
    profileViews: 1520,
    portfolioViews: 4100,
  },
  {
    id: "ph-sarah-thomas",
    slug: "sarah-thomas",
    name: "Sarah Thomas",
    profilePhoto:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=1400&q=80",
    location: "Trivandrum",
    bio: "Romantic proposal and anniversary specialist creating cinematic couple moments.",
    experience: "Known for surprise-friendly setups and golden-hour couple sessions.",
    yearsOfExperience: 7,
    specializations: ["Couples", "Golden Hour", "Proposal"],
    eventTypes: ["Proposal", "Anniversary", "Engagement"],
    portfolio: portfolioPool.slice(0, 7).map((url, i) => ({
      url,
      caption: `Romance ${i + 1}`,
      eventType: "Proposal",
      order: i,
    })),
    startingPrice: 15000,
    languages: ["English", "Malayalam"],
    serviceLocations: ["Trivandrum", "Kovalam", "Varkala"],
    availability: "Available",
    packages: [
      {
        name: "Yes Moment",
        price: 15000,
        hours: 2,
        description: "Proposal coverage with discreet second shooter option.",
        includes: ["1 photographer", "Reveal sequence", "Same-day sneak peeks"],
      },
    ],
    rating: 5.0,
    reviewCount: 22,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: true,
    status: "APPROVED" as const,
    subscriptionPlan: "PREMIUM" as const,
    profileViews: 1100,
    portfolioViews: 2800,
  },
  {
    id: "ph-dev-krishnan",
    slug: "dev-krishnan",
    name: "Dev Krishnan",
    profilePhoto:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=1400&q=80",
    location: "Mysuru",
    bio: "Creative themed-party photographer who loves bold colours, props and playful storytelling.",
    experience: "Covers themed birthdays, graduation parties and creative private events.",
    yearsOfExperience: 4,
    specializations: ["Themed Events", "Creative Portraits", "Colour Grading"],
    eventTypes: ["Themed Party", "Birthday", "Graduation", "Kids Party"],
    portfolio: portfolioPool.slice(3, 10).map((url, i) => ({
      url,
      caption: `Theme ${i + 1}`,
      eventType: "Themed Party",
      order: i,
    })),
    startingPrice: 9000,
    languages: ["English", "Kannada", "Hindi"],
    serviceLocations: ["Mysuru", "Bengaluru", "Mandya"],
    availability: "Available",
    packages: [
      {
        name: "Theme Pop",
        price: 9000,
        hours: 3,
        description: "Fun, colourful coverage for themed celebrations.",
        includes: ["1 photographer", "Creative edits", "Online gallery"],
      },
    ],
    rating: 4.5,
    reviewCount: 14,
    socialLinks: { instagram: "https://instagram.com" },
    verified: false,
    featured: false,
    status: "APPROVED" as const,
    subscriptionPlan: "FREE" as const,
    profileViews: 320,
    portfolioViews: 780,
  },
  {
    id: "ph-nisha-fernandes",
    slug: "nisha-fernandes",
    name: "Nisha Fernandes",
    profilePhoto:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=1400&q=80",
    location: "Mangalore",
    bio: "Warm engagement and wedding photographer blending classic portraits with candid storytelling.",
    experience: "8+ years covering coastal weddings and multi-day family functions.",
    yearsOfExperience: 9,
    specializations: ["Wedding", "Portraits", "Multi-day Events"],
    eventTypes: ["Wedding", "Engagement", "Family Function"],
    portfolio: portfolioPool.slice(0, 9).map((url, i) => ({
      url,
      caption: `Wedding ${i + 1}`,
      eventType: "Wedding",
      order: i,
    })),
    startingPrice: 22000,
    languages: ["English", "Konkani", "Kannada", "Hindi"],
    serviceLocations: ["Mangalore", "Udupi", "Goa"],
    availability: "Booked",
    packages: [
      {
        name: "Wedding Day",
        price: 45000,
        hours: 10,
        description: "Full wedding day coverage with second shooter.",
        includes: ["2 photographers", "400+ edits", "Teaser film add-on"],
      },
    ],
    rating: 4.9,
    reviewCount: 51,
    socialLinks: { instagram: "https://instagram.com", facebook: "https://facebook.com" },
    verified: true,
    featured: true,
    status: "APPROVED" as const,
    subscriptionPlan: "PREMIUM" as const,
    profileViews: 2100,
    portfolioViews: 5200,
  },
  {
    id: "ph-vikram-singh",
    slug: "vikram-singh",
    name: "Vikram Singh",
    profilePhoto:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=1400&q=80",
    location: "Hyderabad",
    bio: "High-energy celebration photographer for birthdays, receptions and grand private parties.",
    experience: "Experienced with large guest counts and fast-paced reception floors.",
    yearsOfExperience: 11,
    specializations: ["Receptions", "Large Events", "Flash Photography"],
    eventTypes: ["Birthday", "Wedding", "Corporate", "Custom Event"],
    portfolio: portfolioPool.map((url, i) => ({
      url,
      caption: `Energy ${i + 1}`,
      eventType: "Birthday",
      order: i,
    })),
    startingPrice: 20000,
    languages: ["English", "Hindi", "Telugu"],
    serviceLocations: ["Hyderabad", "Secunderabad", "Warangal"],
    availability: "Available",
    packages: [
      {
        name: "Grand Night",
        price: 28000,
        hours: 6,
        description: "Reception and party floor coverage.",
        includes: ["1 photographer", "Flash kit", "Quick previews"],
      },
    ],
    rating: 4.4,
    reviewCount: 33,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: false,
    status: "APPROVED" as const,
    subscriptionPlan: "PRO" as const,
    profileViews: 760,
    portfolioViews: 1900,
  },
  {
    id: "ph-aisha-rahman",
    slug: "aisha-rahman",
    name: "Aisha Rahman",
    profilePhoto:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=1400&q=80",
    location: "Chennai",
    bio: "Minimal, modern aesthetic for intimate engagements and stylish private celebrations.",
    experience: "Focuses on refined compositions and contemporary couple storytelling.",
    yearsOfExperience: 5,
    specializations: ["Minimal", "Modern Couples", "Editorial"],
    eventTypes: ["Engagement", "Anniversary", "Proposal", "Custom Event"],
    portfolio: portfolioPool.slice(1, 8).map((url, i) => ({
      url,
      caption: `Modern ${i + 1}`,
      eventType: "Engagement",
      order: i,
    })),
    startingPrice: 16000,
    languages: ["English", "Tamil", "Hindi"],
    serviceLocations: ["Chennai", "Mahabalipuram", "Pondicherry"],
    availability: "Available",
    packages: [
      {
        name: "Modern Love",
        price: 16000,
        hours: 3,
        description: "Styled engagement and anniversary sessions.",
        includes: ["1 photographer", "Curated edits", "Print-ready files"],
      },
    ],
    rating: 4.8,
    reviewCount: 17,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: false,
    status: "APPROVED" as const,
    subscriptionPlan: "PRO" as const,
    profileViews: 540,
    portfolioViews: 1200,
  },
  {
    id: "ph-leo-mathew",
    slug: "leo-mathew",
    name: "Leo Mathew",
    profilePhoto:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&q=80",
    coverImage:
      "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=1400&q=80",
    location: "Kalpetta, Wayanad",
    bio: "Local Wayanad photographer capturing family functions, birthdays and destination micro-events in the hills.",
    experience: "Deep local knowledge of venues and lighting across Wayanad.",
    yearsOfExperience: 3,
    specializations: ["Destination", "Family", "Outdoor"],
    eventTypes: ["Birthday", "Family Function", "Surprise", "Custom Event"],
    portfolio: portfolioPool.slice(2, 8).map((url, i) => ({
      url,
      caption: `Wayanad ${i + 1}`,
      eventType: "Family Function",
      order: i,
    })),
    startingPrice: 8000,
    languages: ["English", "Malayalam"],
    serviceLocations: ["Kalpetta", "Sulthan Bathery", "Mananthavady"],
    availability: "Available",
    packages: [
      {
        name: "Hills & Home",
        price: 8000,
        hours: 3,
        description: "Affordable local coverage for family celebrations.",
        includes: ["1 photographer", "80 edits", "WhatsApp delivery"],
      },
    ],
    rating: 4.6,
    reviewCount: 11,
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: false,
    status: "APPROVED" as const,
    subscriptionPlan: "FREE" as const,
    profileViews: 410,
    portfolioViews: 900,
  },
] as const;

export const DEMO_REVIEWS = [
  {
    id: "rev-1",
    name: "Priya Menon",
    avatar:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80",
    rating: 5,
    review:
      "ShapeMyMoments handled our anniversary from décor to photography. We actually enjoyed the evening instead of managing vendors.",
    eventType: "Anniversary" as const,
    photographerId: "ph-ananya-rao",
    packageId: "pkg-intimate-romance",
    status: "APPROVED" as const,
    featured: true,
    date: "2025-11-12",
  },
  {
    id: "rev-2",
    name: "Rohit Sharma",
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    rating: 5,
    review:
      "Our daughter's birthday was stress-free. The team coordinated cake, décor and photos perfectly within budget.",
    eventType: "Birthday" as const,
    photographerId: "ph-arjun-nair",
    packageId: "pkg-birthday-essentials",
    status: "APPROVED" as const,
    featured: true,
    date: "2025-12-03",
  },
  {
    id: "rev-3",
    name: "Anjali Nair",
    rating: 5,
    review:
      "The surprise proposal setup was magical. Discreet coordination and beautiful photography — she said yes!",
    eventType: "Proposal" as const,
    photographerId: "ph-sarah-thomas",
    packageId: "pkg-intimate-romance",
    status: "APPROVED" as const,
    featured: true,
    date: "2026-01-18",
  },
  {
    id: "rev-4",
    name: "Farah Khan",
    rating: 4,
    review:
      "Baby shower styling was soft and elegant. Guests kept asking who planned it.",
    eventType: "Baby Shower" as const,
    photographerId: "ph-meera-joseph",
    packageId: "pkg-baby-bloom",
    status: "APPROVED" as const,
    featured: false,
    date: "2026-02-02",
  },
  {
    id: "rev-5",
    name: "Sandeep Kumar",
    rating: 5,
    review:
      "Corporate offsite looked polished. Clear communication and on-time execution throughout.",
    eventType: "Corporate" as const,
    photographerId: "ph-rahul-menon",
    packageId: "pkg-corporate-gather",
    status: "APPROVED" as const,
    featured: true,
    date: "2026-02-20",
  },
  {
    id: "rev-6",
    name: "Lakshmi R",
    rating: 5,
    review:
      "Wedding planning felt like having a trusted partner. Every detail was handled with care.",
    eventType: "Wedding" as const,
    photographerId: "ph-nisha-fernandes",
    packageId: "pkg-signature",
    status: "APPROVED" as const,
    featured: true,
    date: "2026-03-08",
  },
  {
    id: "rev-7",
    name: "Imran Ali",
    rating: 4,
    review:
      "Kids party was chaotic in the best way — and we didn't have to manage any of it.",
    eventType: "Kids Party" as const,
    photographerId: "ph-dev-krishnan",
    packageId: "pkg-kids-magic",
    status: "APPROVED" as const,
    featured: false,
    date: "2026-03-22",
  },
  {
    id: "rev-8",
    name: "Neha Patel",
    rating: 5,
    review:
      "Transparent planning and beautiful final result. Celebration Plus was worth every rupee.",
    eventType: "Engagement" as const,
    packageId: "pkg-celebration-plus",
    status: "APPROVED" as const,
    featured: true,
    date: "2026-04-01",
  },
  {
    id: "rev-9",
    name: "Jose Thomas",
    rating: 5,
    review:
      "Local Wayanad coverage was excellent. Leo knew the perfect spots for family photos.",
    eventType: "Family Function" as const,
    photographerId: "ph-leo-mathew",
    status: "APPROVED" as const,
    featured: false,
    date: "2026-04-15",
  },
  {
    id: "rev-10",
    name: "Divya Krishnan",
    rating: 5,
    review:
      "From first call to final celebration, ShapeMyMoments made everything effortless.",
    eventType: "Custom Event" as const,
    packageId: "pkg-signature",
    status: "APPROVED" as const,
    featured: true,
    date: "2026-05-10",
  },
] as const;

export const DEMO_FAQS = [
  {
    question: "What does ShapeMyMoments actually handle?",
    answer:
      "We plan, source, arrange, coordinate and manage your event end-to-end — décor, vendors, photography, catering coordination and on-day execution based on your brief and budget.",
  },
  {
    question: "How does custom event planning work?",
    answer:
      "Share your vision through Plan My Event. Our team reviews your date, location, guest count, budget and required services, then builds a customized package and quotation.",
  },
  {
    question: "Can I only book a photographer?",
    answer:
      "Yes. Browse our photographer directory, view portfolios and request a photographer directly — or include photography as part of a full event package.",
  },
  {
    question: "How far in advance should I book?",
    answer:
      "We recommend 3–6 weeks for most celebrations and longer for weddings or peak dates. Surprise events can often be arranged faster depending on availability.",
  },
  {
    question: "Do you work within a fixed budget?",
    answer:
      "Absolutely. Tell us your budget upfront and we design a realistic plan — prioritizing what matters most to you.",
  },
  {
    question: "Where do you currently operate?",
    answer:
      "We primarily serve Wayanad, Kozhikode and nearby Kerala locations, with selective coverage across South India for premium packages.",
  },
] as const;

export const DEMO_EVENT_REQUESTS = [
  {
    id: "er-1",
    requestId: "SMM-260901-A1B2C3",
    eventType: "Birthday",
    eventDate: "2026-10-20",
    location: "Kalpetta",
    expectedGuests: 30,
    budget: 50000,
    duration: "4 hours",
    services: ["Decoration", "Photography", "Cake", "Entertainment"],
    vision: "Luxury pink theme kids birthday with soft décor and candid photos.",
    theme: "Luxury Pink",
    name: "Anitha R",
    email: "anitha@example.com",
    phone: "9876543210",
    whatsapp: "9876543210",
    preferredContact: "WhatsApp",
    status: "NEW",
    createdAt: "2026-09-01T10:00:00.000Z",
  },
  {
    id: "er-2",
    requestId: "SMM-260828-D4E5F6",
    eventType: "Anniversary",
    eventDate: "2026-09-28",
    location: "Kochi",
    expectedGuests: 20,
    budget: 35000,
    duration: "3 hours",
    services: ["Decoration", "Photography", "Music", "Event Coordination"],
    vision: "Intimate 10th anniversary dinner with romantic décor.",
    name: "Vivek S",
    email: "vivek@example.com",
    phone: "9988776655",
    preferredContact: "Phone",
    status: "PLANNING",
    createdAt: "2026-08-28T14:20:00.000Z",
  },
] as const;
